### ISSUE TITLE
mac导出时页边距异常

### ISSUE THREAD

**Issue by Simohara** [yfzhao20/Typora-markdown#2]
编辑时
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/15936122/119159046-d3b7e280-ba91-11eb-9ff2-503935bdcaf9.png">

导出后
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/15936122/119159139-ee8a5700-ba91-11eb-9545-c348994e2435.png">

**Comment by yfzhao20** [comment]
这个似乎是Typora的问题，我用Windows也是这样。试过多个样式，但是无法很好地修改页边距。

在Typora的导出设置（0.10.6及以后）中有这么一项：

![image](https://user-images.githubusercontent.com/80528249/119222449-ffd17300-bb26-11eb-8129-9dc188a88c97.png)

但是好像并没有什么用处……之后可能会取消掉css中的打印页面样式（@media这些），利用自带的功能再试试。

**Comment by yfzhao20** [comment]
已经试着修复了，可以试试看。如果问题解决，我将关闭这个问题

**Comment by Simohara** [comment]
调了之后页边距是窄了，还是有一些微妙的差距

**Comment by Simohara** [comment]
解决了,感谢
